codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 100.0
        threshold: 0
    patch:
      default:
        branches: null
fixes:
  - "/opt/::"
